# Generated by Django 5.2.7 on 2025-12-03 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_remove_post_username_post_author'),
        ('Users', '0003_useraccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
