# Generated by Django 5.2.7 on 2025-10-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=100)),
                ('happy', models.BooleanField(default=False)),
                ('sad', models.BooleanField(default=False)),
                ('angry', models.BooleanField(default=False)),
                ('excited', models.BooleanField(default=False)),
                ('anxious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
