# Generated by Django 5.2.7 on 2025-12-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moods', '0003_alter_mood_options_mood_intensity_mood_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='intensity',
        ),
    ]
